version: "3.7"

services:
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes: 
      - .:/usr/app
    command: yarn dev
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  
  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
     - 6003:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'eduardo.svilke@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:
    driver: local
  pgadmin4:
    driver: local